@TheChienHouse_HostAddress = https://localhost:7291

POST {{TheChienHouse_HostAddress}}/api/menuitems
Content-Type: application/json

{
    "name": "spot prawn carpaccio",
    "price": 420,
    "dishType": "Appetizer"
}

###

GET {{TheChienHouse_HostAddress}}/api/menuitems

###

POST {{TheChienHouse_HostAddress}}/api/sales
Content-Type: application/json

{
  "LineItems": [
    {
      "ProductId": 1, 
      "Quantity": 3
    },
    {
      "ProductId": 2, 
      "Quantity": 2
    }
  ]
}

###
