@TheChienHouse_HostAddress = https://localhost:7291

POST {{TheChienHouse_HostAddress}}/api/menuitems
Content-Type: application/json

{
    "name": "ChocolateCake",
    "price": 420,
    "dishType": "Dessert"
}

###

GET {{TheChienHouse_HostAddress}}/api/menuitems
{
}
###

POST {{TheChienHouse_HostAddress}}/api/sales
Content-Type: application/json

{
  "LineItems": [
    {
      "ProductId": 1, 
      "Quantity": 1,
      "MenuItemForSale": "ChocolateCake"
    },
    {
      "ProductId": 2, 
      "Quantity": 2,
      "MenuItemForSale": "SpotPrawnBisque"
    }
  ]
}

###
