@TheChienHouse_HostAddress = https://localhost:7291

POST {{TheChienHouse_HostAddress}}/api/menuitems
Content-Type: application/json

{
    "name": "ChocolateCake",
    "price": 420,
    "dishType": "Dessert"
}

###

GET {{TheChienHouse_HostAddress}}/api/menuitems
{
}
###

POST {{TheChienHouse_HostAddress}}/api/sales
Content-Type: application/json

{
  "LineItems": [
    {
      "ProductId": 1, 
      "Quantity": 1,
      "MenuItemForSale": "ChocolateCake"
    },
    {
      "ProductId": 2, 
      "Quantity": 2,
      "MenuItemForSale": "SpotPrawnBisque"
    }
  ]
}
###

POST {{TheChienHouse_HostAddress}}/api/eventforms
Content-Type: application/json
{
    "EventType": "Party",
    "DietaryRestrictions": ["None"],
    "ClientId": "b1a7c8e2-1234-4cde-9abc-1234567890ab",
    "EventDate": "2026-02-02T22:00:00",
    "ClientName": "Marcus",
    "ClientEmail": "TestEmail@Test.Com",
    "ClientPhoneNumber": "4165127176",
    "Status": "Confirmed"
}

###

GET {{TheChienHouse_HostAddress}}/api/eventforms/form/{id}
Content-Type: application/json
{
    "Id": ""
}