@LightspeedTakeHome_HostAddress = https://localhost:7291

POST {{LightspeedTakeHome_HostAddress}}/api/products
Content-Type: application/json

{
    "name": "lightspeedProduct",
    "price": 420
}

###

GET {{LightspeedTakeHome_HostAddress}}/api/products

###

@id = 1
GET {{LightspeedTakeHome_HostAddress}}/api/products/{{id}}

###
